# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Ifunction": "00_functions.ipynb",
         "himmelblau": "00_functions.ipynb",
         "eggholder": "00_functions.ipynb",
         "mc_cormick": "00_functions.ipynb",
         "holder_table": "00_functions.ipynb",
         "beale": "00_functions.ipynb",
         "saddle_point": "00_functions.ipynb",
         "Function": "00_functions.ipynb",
         "contour": "01_graphics.ipynb",
         "zoom": "01_graphics.ipynb",
         "rotate": "01_graphics.ipynb",
         "__log_contour_levels": "01_graphics.ipynb",
         "plot_function_3d": "01_graphics.ipynb",
         "plot_interactive": "01_graphics.ipynb",
         "plot_function_2d": "01_graphics.ipynb",
         "plot_function": "01_graphics.ipynb",
         "plot_all_functions": "01_graphics.ipynb",
         "tuple_float_cast": "02_optimizers.ipynb",
         "History": "02_optimizers.ipynb",
         "optimize": "02_optimizers.ipynb",
         "optimize_multi": "02_optimizers.ipynb"}

modules = ["functions.py",
           "graphics.py",
           "optimizers.py"]

doc_url = "https://clungu.github.io/optimisations/"

git_url = "https://github.com/clungu/optimisations/tree/master/"

def custom_doc_links(name): return None
