# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://clungu.github.io/optimisations/"

git_url = "https://github.com/clungu/optimisations/tree/master/"

def custom_doc_links(name): return None
