# AUTOGENERATED! DO NOT EDIT! File to edit: ../07_genetic_comparison.ipynb.

# %% auto #0
__all__ = ['ComparisonResult', 'compare_genetic']

# %% ../07_genetic_comparison.ipynb #comparison-imports
from dataclasses import dataclass
from numbers import Integral, Real

import numpy as np

from optimisations.genetic import Diagnostics, genetic_algo

# %% ../07_genetic_comparison.ipynb #comparison-result
@dataclass(frozen=True)
class ComparisonResult:
    """One seeded run; its read-only best-loss curve includes partial generations.

    Population diversity (fraction of distinct coordinate pairs), generation
    count and diagnostics describe only the last completed state/updates.
    The final interrupted update is not included in diagnostics_history.
    DE diagnostics exclude its initial population evaluation, have no exponent
    histogram, and count invalid objective proposals, not non-improving trials.
    Their shared mutation_displacement field is an unused zero; the result's
    mutation_displacement property returns None for DE.
    """

    seed: int
    method: str
    evaluations: int
    best_loss: float
    best_params: tuple[float, float]
    best_loss_history: np.ndarray
    nonfinite_evaluations: int
    completed_generations: int
    population_diversity: float
    diagnostics_history: tuple[Diagnostics, ...]

    @property
    def completed_evaluations(self):
        """Objective calls recorded by completed-update diagnostics only."""
        return sum(item.evaluations for item in self.diagnostics_history)

    @property
    def rejection_rate(self):
        """Invalid proposals / attempted offspring across completed updates."""
        attempted = sum(item.offspring for item in self.diagnostics_history)
        rejected = sum(item.rejected for item in self.diagnostics_history)
        return rejected / attempted if attempted else 0.0

    @property
    def mutation_displacement(self):
        """Mean completed-update GA displacement; None for DE or no updates."""
        if self.method == 'differential_evolution' or not self.diagnostics_history:
            return None
        return float(np.mean([item.mutation_displacement for item in self.diagnostics_history]))

    @property
    def exponent_histogram(self):
        """Last completed update's raw biased-exponent counts, if available."""
        return self.diagnostics_history[-1].exponent_histogram if self.diagnostics_history else ()

# %% ../07_genetic_comparison.ipynb #comparison-budget
class _EvaluationLimit(Exception):
    pass


class _BudgetObjective:
    def __init__(self, objective, limit):
        self.objective = objective
        self.limit = limit
        self.evaluations = 0
        self.nonfinite_evaluations = 0
        self.best_loss = np.inf
        self.best_params = None
        self.history = []

    def __call__(self, x, y):
        if self.evaluations >= self.limit:
            raise _EvaluationLimit
        self.evaluations += 1
        loss = np.asarray(self.objective(x, y))
        if loss.shape != () or loss.dtype.kind not in 'iuf':
            raise ValueError('objective(x, y) must return a real scalar')
        value = float(loss)
        if not np.isfinite(value):
            self.nonfinite_evaluations += 1
        elif value < self.best_loss:
            self.best_loss = value
            self.best_params = (float(x), float(y))
        self.history.append(self.best_loss)
        return value


def _comparison_result(seed, method, tracked, population, diagnostics):
    curve = np.asarray(tracked.history, dtype=np.float64)
    curve.setflags(write=False)
    return ComparisonResult(
        seed=seed, method=method, evaluations=tracked.evaluations,
        best_loss=tracked.best_loss, best_params=tracked.best_params,
        best_loss_history=curve, nonfinite_evaluations=tracked.nonfinite_evaluations,
        completed_generations=len(diagnostics),
        population_diversity=len(np.unique(population, axis=0)) / len(population),
        diagnostics_history=tuple(diagnostics))


def _integer_option(value, name, minimum):
    if (isinstance(value, (bool, np.bool_)) or not isinstance(value, Integral)
            or value < minimum):
        raise ValueError(f'{name} must be an integer >= {minimum}')
    return int(value)


def _comparison_options(objective, start, seeds, evaluation_budget, population_size,
                        max_offset, expected_mutations, max_retries):
    if not callable(objective):
        raise ValueError('objective must be callable as objective(x, y)')
    population_size = _integer_option(population_size, 'population_size', 4)
    evaluation_budget = _integer_option(evaluation_budget, 'evaluation_budget', population_size)
    if (isinstance(expected_mutations, (bool, np.bool_))
            or not isinstance(expected_mutations, Real)
            or not 0 <= expected_mutations <= 48):
        raise ValueError('expected_mutations must be a finite real number in [0, 48]')
    expected_mutations = float(expected_mutations)
    try:
        seeds = tuple(seeds)
    except TypeError as error:
        raise ValueError('seeds must be a nonempty iterable of nonnegative integers') from error
    if not seeds:
        raise ValueError('seeds must be a nonempty iterable of nonnegative integers')
    seeds = tuple(_integer_option(seed, 'seed', 0) for seed in seeds)
    # Reuse the public GA's validation and bounds policy before any objective call.
    if max_offset is None:
        raise ValueError('max_offset must be a finite real number')
    init, _, _ = genetic_algo(population_size, max_offset,
                              mutation_chance=expected_mutations / 48,
                              seed=0, max_retries=max_retries)
    bounds = init(start).bounds.copy()
    start = np.asarray(start, dtype=np.float64).copy()
    return start, bounds, seeds, evaluation_budget, population_size, expected_mutations

# %% ../07_genetic_comparison.ipynb #comparison-runners
def _run_ga(tracked, start, seed, method, population_size, max_offset,
            expected_mutations, max_retries):
    encoding = 'fixed' if method == 'fixed' else 'ieee754'
    operators = 'guarded' if method == 'ieee754_guarded' else 'standard'
    bits = 48 if encoding == 'fixed' else 128
    init, update, get_params = genetic_algo(
        population_size, max_offset, mutation_chance=expected_mutations / bits,
        seed=seed, encoding=encoding, operators=operators, max_retries=max_retries,
        exploration_chance=0)
    state = init(start)
    diagnostics = []
    try:
        while tracked.evaluations < tracked.limit:
            state = update(len(diagnostics), tracked, state)
            diagnostics.append(state.diagnostics)
    except _EvaluationLimit:
        pass
    return _comparison_result(seed, method, tracked, get_params(state), diagnostics)


def _run_differential_evolution(tracked, start, bounds, seed, population_size):
    rng = np.random.default_rng(seed)
    width = bounds[1] - bounds[0]
    unit_population = rng.random((population_size, 2))
    population = bounds[0] + unit_population * width
    population[0] = start
    unit_population[0] = np.divide(start - bounds[0], width,
                                   out=np.zeros(2), where=width != 0)
    losses = np.empty(population_size)
    for index, (x, y) in enumerate(population):
        losses[index] = tracked(x, y)
        if not np.isfinite(losses[index]):
            raise ValueError('initial objective(x, y) must return a finite real scalar')
    diagnostics = []
    try:
        while tracked.evaluations < tracked.limit:
            next_unit, next_population, next_losses = (
                unit_population.copy(), population.copy(), losses.copy())
            rejected_objective = 0
            for index in range(population_size):
                available = np.delete(np.arange(population_size), index)
                r1, r2, r3 = rng.choice(available, 3, replace=False)
                donor = unit_population[r1] + 0.8 * (unit_population[r2] - unit_population[r3])
                donor = np.clip(donor, 0, 1)
                cross = rng.random(2) < 0.9
                cross[rng.integers(2)] = True
                trial_unit = np.where(cross, donor, unit_population[index])
                trial = np.clip(bounds[0] + trial_unit * width, bounds[0], bounds[1])
                loss = tracked(*trial)
                if not np.isfinite(loss):
                    rejected_objective += 1
                elif loss <= losses[index]:
                    next_unit[index], next_population[index], next_losses[index] = trial_unit, trial, loss
            unit_population, population, losses = next_unit, next_population, next_losses
            diagnostics.append(Diagnostics(
                evaluations=population_size, offspring=population_size,
                rejected_objective=rejected_objective, retained_parents=rejected_objective))
    except _EvaluationLimit:
        pass
    return _comparison_result(seed, 'differential_evolution', tracked, population, diagnostics)

# %% ../07_genetic_comparison.ipynb #comparison-api
def compare_genetic(objective, start, *, seeds=(0, 1, 2), evaluation_budget=2000,
                    population_size=50, max_offset=4, expected_mutations=0.48,
                    max_retries=8):
    """Compare three GA representations and NumPy DE under exact call budgets.

    Return one ComparisonResult per seed/method, in seed order then fixed,
    ieee754, ieee754_guarded, differential_evolution order. Seeds must be a
    nonempty finite iterable of nonnegative integers. Every run shares the
    same bounded initial sampling (apart from fixed-point quantisation).

    population_size must be >= 4; evaluation_budget >= population_size.
    expected_mutations must lie in [0, 48]. Objective calls and best curves
    include interrupted updates; population/diagnostics exclude them.
    Nonfinite initial losses and invalid configuration raise ValueError;
    fixed-point additionally requires finite losses at every evaluation.
    User objective exceptions propagate unchanged.
    """
    start, bounds, seeds, evaluation_budget, population_size, expected_mutations = _comparison_options(
        objective, start, seeds, evaluation_budget, population_size,
        max_offset, expected_mutations, max_retries)
    results = []
    for seed in seeds:
        for method in ('fixed', 'ieee754', 'ieee754_guarded', 'differential_evolution'):
            tracked = _BudgetObjective(objective, evaluation_budget)
            if method == 'differential_evolution':
                result = _run_differential_evolution(tracked, start, bounds, seed, population_size)
            else:
                result = _run_ga(tracked, start, seed, method, population_size, max_offset,
                                 expected_mutations, max_retries)
            results.append(result)
    return results
