# AUTOGENERATED! DO NOT EDIT! File to edit: ../06_genetic_algorithm.ipynb.

# %% auto #0
__all__ = ['State', 'get_params', 'genetic_algo']

# %% ../06_genetic_algorithm.ipynb #ga-imports
from copy import deepcopy
from dataclasses import dataclass
from numbers import Integral, Real

import numpy as np

_BITS_PER_COORDINATE = 24
_MAX_GENE = (1 << _BITS_PER_COORDINATE) - 1
_BIT_SHIFTS = np.arange(_BITS_PER_COORDINATE - 1, -1, -1, dtype=np.uint32)
_BIT_WEIGHTS = np.uint32(1) << _BIT_SHIFTS

# %% ../06_genetic_algorithm.ipynb #ga-state
@dataclass(frozen=True)
class State:
    """A population snapshot: binary DNA, [lower, upper] bounds and private RNG state.

    Fitness is None until the first update, then the negative objective per individual.
    Treat arrays and the RNG dictionary as read-only; updates never modify them.
    """

    generation: np.ndarray
    bounds: np.ndarray
    rng_state: dict
    fitness: np.ndarray | None = None

# %% ../06_genetic_algorithm.ipynb #ga-encoding
def _encode(params, bounds):
    params = np.asarray(params, dtype=np.float64)
    width = bounds[1] - bounds[0]
    fractions = np.divide(params - bounds[0], width,
                          out=np.zeros_like(params), where=width != 0)
    genes = np.rint(np.clip(fractions, 0, 1) * _MAX_GENE).astype(np.uint32)
    return ((genes[..., None] >> _BIT_SHIFTS) & 1).reshape(-1, 48).astype(np.uint8)


def _decode(generation, bounds):
    genes = generation.reshape(-1, 2, _BITS_PER_COORDINATE) @ _BIT_WEIGHTS
    params = bounds[0] + (genes / _MAX_GENE) * (bounds[1] - bounds[0])
    return np.clip(params, bounds[0], bounds[1])


def _real_option(value, name, minimum, maximum=None):
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Real):
        raise ValueError(f'{name} must be a finite real number')
    try:
        value = float(value)
    except OverflowError as error:
        raise ValueError(f'{name} must be finite') from error
    if not np.isfinite(value) or value < minimum or (maximum is not None and value > maximum):
        limit = f'[{minimum}, {maximum}]' if maximum is not None else f'>= {minimum}'
        raise ValueError(f'{name} must be finite and {limit}')
    return value


def _starting_bounds(params, max_offset):
    try:
        params = np.asarray(params)
    except (TypeError, ValueError) as error:
        raise ValueError('params must contain exactly two finite real numbers') from error
    if params.shape != (2,) or params.dtype.kind not in 'iuf':
        raise ValueError('params must contain exactly two finite real numbers')
    with np.errstate(over='ignore', invalid='ignore'):
        params = params.astype(np.float64)
        bounds = np.array([params - max_offset, params + max_offset])
        width = bounds[1] - bounds[0]
    if not np.all(np.isfinite(params)):
        raise ValueError('params must contain exactly two finite real numbers')
    if (not np.all(np.isfinite(bounds)) or not np.all(np.isfinite(width))
            or (max_offset > 0 and np.any(width <= 0))):
        raise ValueError('max_offset must give finite, representable, nondegenerate bounds')
    return params, bounds

# %% ../06_genetic_algorithm.ipynb #ga-params
def get_params(state):
    """Decode a snapshot into a fresh float64 array of shape (population_size, 2)."""
    return _decode(state.generation, state.bounds)

# %% ../06_genetic_algorithm.ipynb #ga-selection
def _evaluate(objective, params):
    if not callable(objective):
        raise ValueError('objective must be callable as objective(x, y)')
    fitness = np.empty(len(params), dtype=np.float64)
    for index, (x, y) in enumerate(params):
        loss = np.asarray(objective(x, y))
        if loss.shape != () or loss.dtype.kind not in 'iuf':
            raise ValueError('objective(x, y) must return a finite real scalar')
        value = float(loss)
        if not np.isfinite(value):
            raise ValueError('objective(x, y) must return a finite real scalar')
        fitness[index] = -value
    return fitness


def _proportional_probabilities(fitness):
    # Scale before subtracting: opposite, very large finite values must not overflow.
    scaled = fitness / max(1.0, np.max(np.abs(fitness)))
    weights = scaled - scaled.min()
    total = weights.sum()
    return weights / total if total > 0 else None


def _crossover(parents, rng):
    children = parents[rng.permutation(len(parents))].copy()
    for first in range(0, len(children) - 1, 2):
        locus = rng.integers(1, children.shape[1])
        children[first:first + 2, locus:] = children[first:first + 2, locus:][::-1].copy()
    return children


def _next_generation(generation, fitness, mutation_chance, rng):
    count = len(generation)
    elite_count = max(1, int(0.3 * count))
    proportional_count = int(0.4 * count)
    tournament_count = count - elite_count - proportional_count
    elites = generation[np.argsort(-fitness, kind='stable')[:elite_count]]
    proportional = rng.choice(count, size=proportional_count, replace=True,
                              p=_proportional_probabilities(fitness))
    competitors = rng.integers(count, size=(tournament_count, 2))
    winners = competitors[np.arange(tournament_count), np.argmax(fitness[competitors], axis=1)]
    parents = generation[np.concatenate([proportional, winners])]
    children = _crossover(parents, rng)
    children ^= rng.random(children.shape) < mutation_chance
    return np.concatenate([elites, children])

# %% ../06_genetic_algorithm.ipynb #ga-factory
def genetic_algo(population_size=50, max_offset=4, *, mutation_chance=0.01, seed=None):
    """Return (init, update, get_params) for bounded, binary genetic minimisation.

    Use with derivatives_based=False. max_offset bounds each coordinate around
    the starting point; coordinates use 24-bit fixed-point precision. A fixed
    seed makes initialisation, restarts and independent runs reproducible.
    """
    if population_size is None:
        population_size = 200
    if (isinstance(population_size, (bool, np.bool_))
            or not isinstance(population_size, Integral) or population_size < 2):
        raise ValueError('population_size must be an integer >= 2, or None')
    population_size = int(population_size)
    max_offset = _real_option(max_offset, 'max_offset', 0)
    mutation_chance = _real_option(mutation_chance, 'mutation_chance', 0, 1)
    initial_rng = np.random.default_rng(seed)
    bit_generator_type = type(initial_rng.bit_generator)
    initial_rng_state = deepcopy(initial_rng.bit_generator.state)

    def restore_rng(rng_state):
        rng = np.random.Generator(bit_generator_type(0))
        rng.bit_generator.state = deepcopy(rng_state)
        return rng

    def init(params):
        params, bounds = _starting_bounds(params, max_offset)
        rng = restore_rng(initial_rng_state)
        population = bounds[0] + rng.random((population_size, 2)) * (bounds[1] - bounds[0])
        population[0] = params
        return State(generation=_encode(population, bounds), bounds=bounds,
                     rng_state=deepcopy(rng.bit_generator.state))

    def update(i, objective, state):
        rng = restore_rng(state.rng_state)
        fitness = _evaluate(objective, get_params(state))
        generation = _next_generation(state.generation, fitness, mutation_chance, rng)
        bounds = state.bounds.copy()
        return State(generation=generation, bounds=bounds,
                     fitness=_evaluate(objective, _decode(generation, bounds)),
                     rng_state=deepcopy(rng.bit_generator.state))

    return init, update, get_params
