# AUTOGENERATED! DO NOT EDIT! File to edit: ../03_optimizers.ipynb.

# %% auto #0
__all__ = ['optimize', 'optimize_multi']

# %% ../03_optimizers.ipynb #9e1aa1ff
import numpy as np
from jax import grad
from functools import partial
from typing import Callable, Union

# %% ../03_optimizers.ipynb #5b12cb81
def tuple_float_cast(_tuple):
    x, y = _tuple
    return round(float(x), 3), round(float(y), 3)

class History(list):
    """
    This object stores the states through which an optimizer has passed through.
    
    Normally we would have just a list for this but because we are storing `jax` states,
    we need to subclass the `__repr__` method so we process the output a bit 
    (displaying the parameters of the state) and not the state in itself
    """
    def __repr__(self):
        if not hasattr(self, '_get_params'):
            return super().__repr__()
        else:
            elements = []
            for state in self:
                params = np.asarray(self._get_params(state))
                elements.append(tuple_float_cast(params) if params.ndim == 1 else np.round(params, 3).tolist())
            return str(elements)

# %% ../03_optimizers.ipynb #7711bcd1
"""
Each class of optimizers has a special calling convention.
It's unfortunte that we can't just subclass the optimizers and inject our custom method
and we need to do this. This happens because the optimziers are written in a pure functional
style, and the methods are just functions that share state between them, back and forth.
"""
def _derivatives_based_update(i, state, update_fn, get_params_fn, grad_fn):
    params = get_params_fn(state)
    grads = grad_fn(*params)
    return update_fn(i, grads, state)

def _derivatives_free_update(i, state, update_fn, function):
    return update_fn(i, function, state)

def heuristic_get_jax_optimizer_name(init):
    """Return the name of a JAX example-library optimiser."""
    return getattr(init, '__qualname__', '').split('.<locals>.')[0].split('.')[-1] or 'optimizer'

# %% ../03_optimizers.ipynb #63a57846
class optimize:
    def __init__(self, function):
        self.function = function
        self.history = History()        

    def using(self, optimizer=(None, None, None), name=None, derivatives_based=True, render_decorator: Callable=None):
        """Configure a triple; derivative-free updates receive the objective, not its gradient."""
        self.derivatives_based = derivatives_based
        self.__init, self.__update, self._get_params = optimizer
        self.render_decorator = render_decorator
        
        # add this to the history object so it can extract the value for presenting them in __repr__
        # otherwise we will see a list of `jax` states
        self.history._get_params = self._get_params
        
        #functional polymorphysm ?!
        if derivatives_based:
            self._update_fn = partial(
                _derivatives_based_update, 
                update_fn=self.__update, 
                get_params_fn=self._get_params,
                grad_fn=grad(self.function, argnums=(0, 1))
            )
        else:
            self._update_fn = partial(
                _derivatives_free_update, 
                update_fn=self.__update, 
                function=self.function
            )

        self.optimizer = optimizer
        self.optimizer_name = name if name is not None else heuristic_get_jax_optimizer_name(self.__init)
        return self


    def start_from(self, params):
        """Initialise, passing the objective only to optimisers that opt in."""
        init_with_objective = getattr(self.__init, 'with_objective', None)
        if not self.derivatives_based and init_with_objective is not None:
            state = init_with_objective(tuple(params), objective=self.function)
        else:
            state = self.__init(tuple(params))
        self.history.clear()
        self.state = state
        self.history.append(self.state)
        return self

    def update(self, nr_iterations=1):
        # we add the initial state as state 0, but we haven't made any udpdates yet
        # so even if we have something in history, the current_iteration is one behind
        current_iteration = len(self.history) - 1   
        for i in range(nr_iterations):
            self.state = self._update_fn(current_iteration + i, self.state)
            self.history.append(self.state)
        return self.history

# %% ../03_optimizers.ipynb #6b2081b2
def build_optimizer_params(elements_list):
    if len(elements_list) == 2 and isinstance(elements_list[1], dict):
        optimizer, options = elements_list
        optimizer_params = dict(options)
    elif len(elements_list) == 1:
        optimizer, = elements_list
        optimizer_params = {}
    elif len(elements_list) == 3:
        optimizer = elements_list
        optimizer_params = {}
    else:
        raise ValueError('Expected an optimizer triple, a one-element list, or a triple and options')
    if len(optimizer) != 3 or not all(callable(fn) for fn in optimizer):
        raise ValueError('Optimizer must contain three callable functions')
    optimizer_params['optimizer'] = optimizer
    optimizer_params.setdefault('name', heuristic_get_jax_optimizer_name(optimizer[0]))
    return optimizer_params

# %% ../03_optimizers.ipynb #451393d4
class optimize_multi:
    def __init__(self, function):
        self.function = function

    def using(self, optimizers):
        self.optimizers = optimizers
        return self

    def start_from(self, params):
        self.params = params
        return self

    def tolist(self):
        return [optimize(self.function).using(**build_optimizer_params(optimizer)).start_from(self.params) for optimizer in self.optimizers]
